apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
    - name: ftps-1
      port: 50110
    - name: ftps-2
      port: 50111
    - name: ftps-3
      port: 50112

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      resources :
      containers:
      - name: ftps
        imagePullPolicy: Never
        image: ftp
        ports:
          - containerPort: 21
          - containerPort: 50110
          - containerPort: 50111
          - containerPort: 50112
    